# Generated by Django 2.1.8 on 2020-06-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', editable=False, max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='task1',
            field=models.BooleanField(default=False),
        ),
    ]
