# Generated by Django 2.1.8 on 2020-06-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20200606_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='right',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
