# Generated by Django 3.0.7 on 2020-06-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20200607_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task1_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='上次点击'),
        ),
        migrations.AddField(
            model_name='task',
            name='task2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='task2_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='上次点击'),
        ),
    ]
